name: derivkit-demos
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - cmasher
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - derivkit @ git+https://github.com/derivkit/derivkit@main
